### ISSUE TITLE
 has a problem on mono

### ISSUE THREAD

**Issue by zhaojie** [castleproject/Core#232] opened 2017-02-10 06:53 UTC
hi, 
on Mono 4.6+  jexus 5.8+  the problem ,

```
{
"message":"An error has occurred.",
"exceptionMessage":"Invalid IL code in Castle.Proxies.Invocations.ApiController_ExecuteAsync_5:InvokeMethodOnTarget (): IL_0023: callvirt  0x0a001057",
"exceptionType":"System.InvalidProgramException",
"stackTrace":"
  at Castle.DynamicProxy.AbstractInvocation.Proceed () [0x0002d] in <cc0e89726f6040e1a646dec1584576ac>:0
  at Abp.WebApi.Controllers.Dynamic.Interceptors.AbpDynamicApiControllerInterceptor`1[T].Intercept (Castle.DynamicProxy.IInvocation invocation) [0x00051] in <299a1b92536d4af1ac38cb06702cb3a5>:0
  at Castle.DynamicProxy.AbstractInvocation.Proceed () [0x000b2] in <cc0e89726f6040e1a646dec1584576ac>:0
  at Castle.Proxies.DynamicApiController`1Proxy_5.ExecuteAsync (System.Web.Http.Controllers.HttpControllerContext controllerContext, System.Threading.CancellationToken cancellationToken) [0x0003d] in <5e1d00e5f02d4889b303c7892d00c0cc>:0
  at System.Web.Http.Dispatcher.HttpControllerDispatcher+<SendAsync>d__1.MoveNext () [0x00123] in <f99f496cb0d249c1a945c1fcabce1695>:0
"
}
```

**Comment by jonorossi** [comment] 2017-02-10 13:28
@zhaojie we need much more info to be able to do anything here. What is "jexus 5.8+"? We need something to reproduce the defect, ideally a unit test that could be added to our codebase to test this situation on Mono.

**Comment by zhaojie** [comment] 2017-02-11 11:41
@jonorossi  Linux ASP.NET Webserver Jexus 5.8.2  http://www.jexus.org

**Comment by jonorossi** [comment] 2017-02-12 12:51
@zhaojie I've reformatted your exception message so it is readable, my guess is that the exception isn't caused by your web server (however web server has no English web site or source code available). You are going to need to isolate things to work out what is causing the problem, it might be caused by `AbpDynamicApiControllerInterceptor` whatever it does, might be a Mono defect, or somewhere else.

I tagged this `needs-repro`, which means that unless you can provide a reproduction of the bug it cannot be investigated. See my previous comment.

**Comment by jonorossi** [comment] 2017-02-21 15:32
Closing as cannot reproduce.

**Closed by jonorossi** 2017-02-21 15:32 UTC
Labels: needs-repro
