### ISSUE TITLE
Hidden base class method is not intercepted

### ISSUE THREAD

**Issue by thomaslevesque** [castleproject/Core#381] opened 2018-06-17 14:50 UTC
Related to FakeItEasy/FakeItEasy#1346.

Consider this code, where a derived class hides a method from the base class:

```csharp
static void Main()
{
    var generator = new ProxyGenerator();
    Derived d = generator.CreateClassProxy<Derived>(new MyInterceptor());
    Base b = d;
    d.Method().Dump();
    b.Method().Dump();
}

class MyInterceptor : IInterceptor
{
    public void Intercept(IInvocation invocation)
    {
        Console.WriteLine($"Intercepting {invocation.Method} on {invocation.InvocationTarget}");
        invocation.Proceed();
    }
}

public class Base
{
    public virtual string Method() => "Base";
}

public class Derived : Base
{
    public virtual new string Method() => "Derived";
}
```

I would expect both `Base.Method` and `Derived.Method` to be intercepted, but it produces the following output:

> Intercepting System.String Method() on Castle.Proxies.DerivedProxy
> Derived
> Base

As you can see, only `Derived.Method` is intercepted.

Is this the expected behavior? Is there any way at all to intercept hidden methods from the base class ?

**Comment by stakx** [comment] 2018-06-17 16:12
I've taken a quick look. The reason why DynamicProxy doesn't intercept `Base.Method` is because it doesn't proxy it, and it doesn't proxy it due to an inaccuracy of `MethodSignatureComparer`. According to that comparer, the two `MethodInfo`s for `Base.Method` and `Derived.Method` compare equal (despite not being equal since they have differing declaring types):

https://github.com/castleproject/Core/blob/69598068cabe759c62f894f6a1e9974772f58ef7/src/Castle.Core/DynamicProxy/Generators/MethodSignatureComparer.cs#L146-L149

This, together with the use of `.Distinct()` in `MethodFinder.GetAllInstanceMethods`, means that one of the two methods will get filtered out as a duplicate and won't be proxied:

https://github.com/castleproject/Core/blob/69598068cabe759c62f894f6a1e9974772f58ef7/src/Castle.Core/DynamicProxy/Generators/MethodFinder.cs#L45-L48

So much for the cause of this current limitation. I haven't yet thought about the possible consequences of making `MethodSignatureComparer` more accurate when comparing two methods for equality. I'm also not yet sure if such a change could break downstream libraries. Will report back once I've done so.

**Comment by stakx** [comment] 2018-06-17 16:34
Actually, as per https://github.com/FakeItEasy/FakeItEasy/issues/1346#issuecomment-397889882, it doesn't seem possible (at the CLR level) to do what is being asked for here, since a proxy type cannot override both `Base.Method` and `Derived.Method`; the latter shadows/hides the former, so `Base.Method` isn't available for overriding. So `MethodSignatureComparer` is likely fine as is.

**Comment by thomaslevesque** [comment] 2018-06-17 16:42
> According to that comparer, the two MethodInfos for Base.Method and Derived.Method compare equal (despite not being equal since they have differing declaring types):

I came to the same conclusion. I tried to change the comparer so that it also takes the declaring type into account, but it still doesn't work. With the fix, both methods are created on the `TypeBuilder`, but `TypeBuilder.CreateTypeInfo()` creates a type with only one of them. So I it's either not supported by the CLR, or `TypeBuilder` has a bug... The former seems more plausible.

**Comment by stakx** [comment] 2018-06-17 16:49
> So I it's either not supported by the CLR

I'm 99% certain that the CLR doesn't support this scenario. 😞

Imagine you have three types:

```csharp
public class Base
{
    public virtual string Method() => "Base";
}

public class Derived : Base
{
    public new virtual string Method() => "Derived";
}

public class DerivedProxy : Derived
{
    public override string Method() => "proxied Derived";
}
```

You can already guess that there's no way in C# to "proxy" both `Base.Method` and `Derived.Method`.

Now let's look at the IL for these:

```
.class public auto ansi beforefieldinit Base extends [mscorlib]System.Object
{
	.method public hidebysig newslot virtual instance string Method() cil managed 
	{
		.maxstack 8
		ldstr "Base"
		ret
	}
}

.class public auto ansi beforefieldinit Derived extends Base
{
	.method public hidebysig newslot virtual instance string Method() cil managed 
	{
		.maxstack 8
		ldstr "Derived"
		ret
	}
}

.class public auto ansi beforefieldinit DerivedProxy extends Derived
{
	.method public hidebysig virtual instance string Method() cil managed 
	{
		.maxstack 8
		ldstr "proxied Derived"
		ret
	}
}
```

AFAIK there is no syntax even in plain IL to override `Base.Method` in `DerivedProxy`.

You can do weird tricks with interface maps but IIRC you cannot use them for non-interface methods.

**Comment by thomaslevesque** [comment] 2018-06-17 16:54
@stakx funny, I did the exact same thing minutes before you posted !
I agree, it doesn't seem possible :(

**Comment by stakx** [comment] 2018-06-17 16:55
@thomaslevesque &mdash; hahah, let's better hope that we've done the right thing then! 😄

**Comment by jonorossi** [comment] 2018-06-20 09:47
Agreed, I see no way to achieve this with the CLR. Closing.

**Closed by jonorossi** 2018-06-20 09:47 UTC
