### ISSUE TITLE
.NET Core - remove AssemblyInfo generation

### ISSUE THREAD

**Issue by jonorossi** [castleproject/Core#133] opened 2016-02-26 04:28 UTC
In our MSBuild scripts we currently generate AssemblyInfo.cs files and they are ignored in Git. Let's get rid of the generation completely and bolster up CommonAssemblyInfo.cs with conditional compilation to do our bidding.

**Comment by blairconrad** [comment] 2016-03-04 11:40
I can take a peek at this.

**Comment by blairconrad** [comment] 2016-03-05 12:51
@jonorossi, I'm looking at the complicated (and so far to me, confusing) generation here, and beginning to have some questions. I'm not held up yet, but some answers may help me go in the right direction. Sorry to be a bother.

What's the goal here? I assume the problem is that we're not running the MsBuild on the NETCORE build, and we'd like a way to have the contents of the AssemblyInfo.cs available to it.

Is there anything else? You specifically against generated files (or generated `AssemblyInfo.cs`es) or is the idea just to get the proper information to the built assemblies?

One reason I ask is that I don't see a way to provide the version numbers without either generating a file to include. I just don't know how else to supply the version numbers from `Settings.csproj`, TeamCity's `Build_number`, or the `Configuration` (feeds into `AssemblyTitle`)

Followup questions:

1. Do you object to restoring _tracked_ project-specific `AssemblyInfo.cs` files if it turns out to be useful?
2. do you know why the SilverLight projects have a different name? This isn't super difficult to achieve. I was just curious.
3. many of the values put in the current `AssemblyInfo.cs` can be overridden at build time. I'm not sure if this is just by convention, or if it's essential. The TeamCity builds don't take advantage, as far as I can tell, except for supplying `Configuration`. For example, `ComVisible` could be supplied (usually `false`, or `AssemblyVersion_Major` (usually same as `Project_Major`). Do you want to keep this flexibility, or could we just hardcode the reasonable defaults?

**Comment by jeremymeng** [comment] 2016-03-08 20:24
@blairconrad I think SiverLight support is going to be dropped so you shouldn't need to worry about it any more.

Some more points for discussion.
- Is it necessary to have version number and build configuration in `AssemblyTitle` and `AssemblyDescription`? if not it would simplify the problem a little bit.

- Most of the assembly information can be achieved using `project.json` if they are static values so maybe the NETCORE project doesn't need `AssemblyInfo.cs`?  The version number needs to be changed every time in `project.json` when bumping the versions though. This is related to #134 if all projects are migrated to use `project.json`-based projects.

**Comment by blairconrad** [comment] 2016-03-08 20:37
@jeremymeng, oh, Silverlight support is going? Let's do that first! If nothing else, it'll speed up our builds and reduce the amount of checking we have to do (everywhere, not just here).
Unfortunately, this is the least of our problems.

> Is it necessary to have version number and build configuration in AssemblyTitle and AssemblyDescription? if not it would simplify the problem a little bit.

It's true. I'd been wondering. Were it my project, I think I'd drop them, but I don't have the history. The castleproject owners may have a good reason to keep them.

> Most of the assembly information can be achieved using project.json if they are static values so maybe the NETCORE project doesn't need AssemblyInfo.cs? 

It's true, but kind of a minor point, I think. For truly static data, we should be able to shove it in `CommonAssemblyInfo.cs`, I'd think. Or even if not that file, _which_ file (and temporarily duplicating files while we switch to project.json seems to me to not be a huge deal) shouldn't make such a big deal.
For things that vary (version numbers, although we could potentially start reading those from `CommonAssemblyInfo.cs` instead), we'll still need to generate something somewhere, whether it's an `AssemblyInfo.cs` type thing or mucking about with `project.jsons`.

The downside to having to generate something is that it keeps people being able to clone and build in the IDE right away. One possibility is to check the file in, tell git to `--assume-unchanged` and then generate what we need on top of the file. 

But that's only an option if @jonorossi and other owners would support generated files.

**Comment by blairconrad** [comment] 2016-03-08 20:39
:blush: as it turns out, I was aware of, but forgot about, the "remove Silverlight" support issue. (#100).

**Comment by jeremymeng** [comment] 2016-03-08 21:16
> For things that vary (version numbers, although we could potentially start reading those from CommonAssemblyInfo.cs instead), we'll still need to generate something somewhere, whether it's an AssemblyInfo.cs type thing or mucking about with project.jsons.

If .csproj are gone in favor or `project.json` then I imagine that the version numbers would be hard-coded in `project.json` files, and be bumped up explicitly.

**Comment by blairconrad** [comment] 2016-03-08 21:19
Currently the version numbers are synchronized for all projects. If understand you correctly, you propose to duplicate in each project.json file? That's a bit of a step backward that I'd think we'd want to avoid…

**Comment by jeremymeng** [comment] 2016-03-08 21:24
Well they represent three separate NuGet packages so it is still debatable whether their version numbers have to be the same, and updated at the same time.

**Comment by blairconrad** [comment] 2016-03-08 21:37
@jeremymeng, it's true, but it's the way it's been done, and my default position is to conform, rather than introduce possibly unrelated or unwanted changes.

**Comment by jeremymeng** [comment] 2016-03-08 21:46
@blairconrad yeah, agree it is best thing to do now.  I was just discussing based on the assumption that csproj would be gone.  That haven't been decided yet.

**Comment by blairconrad** [comment] 2016-03-09 13:19
Silverlight support has been removed with the closing of #100, so that's one less thing to worry about.

**Comment by jonorossi** [comment] 2016-03-09 16:18
@blairconrad @jeremymeng sorry for not answering your questions directly since there are so many, please ask any of them again if this post doesn't answer them.

Since I didn't know exactly what I think we needed to give you an answer without actually looking into I've done a PR, please take a look at #151 and let me know what you think.

The .NET Core build currently fails building with SerilogIntegration because Serilog is no longer CLS compilant, see https://github.com/serilog/serilog/issues/687.

**Comment by blairconrad** [comment] 2016-03-09 23:31
Aside from spun-off #152, is there more to do on this? I had expected the merge of #151 to close this.

**Closed** 2016-03-10 04:40 UTC
Labels: up-for-grabs
