### ISSUE TITLE
Could not find method overriding ***. This is most likely a bug. Please report it.

### ISSUE THREAD

**Issue by backjacklao** [castleproject/Core#538] opened 2020-12-01 06:27 UTC
> Could not find method overriding ***. This is most likely a bug. Please report it.

`IInvocation.MethodInvocationTarget` will throw an exception of type `System.ArgumentException | System.Reflection.MethodInfo {System.ArgumentException}`

#### Method Base Class:

```csharp
public virtual async Task GetPageListAsync(OrderBy<TEntity, T2, T3, T4>[] orderBys){
    return;
}
```

#### Method implementing class:

```
public override async Task GetPageListAsync(OrderBy<TEntity, T2, T3, T4>[] orderBys){
    return;
}
```

`OrderBy<>` is my class

I found , if `OrderBy<TEntity, T2, T3, T4>[]` change to `OrderBy<TEntity, T2, T3, T4>` or `OrderBy<TEntity>` is OK, and if delete the method implementing is also OK.

This issue still occurs in Castle.Core (4.4.1) 

This issue looks like issue #297.

**Comment by stakx** [comment] 2020-12-01 08:53
Hi, it's difficult piecing together what exactly led to that error message from your description. Could you please provide a short but complete repro code example?

**Comment by backjacklao** [comment] 2020-12-05 02:44
Method Base Class:
public virtual async Task GetPageListAsync((Dictionary<string, string>[] test){
return;
}

Method implementing class:
public override async Task GetPageListAsync(Dictionary<string, string>[] test){
return;
}

IInterceptor implementing class:
public class MyInterceptor : IInterceptor
    {
        public void Intercept(IInvocation invocation)
        {
            MethodInfo methodInfo = invocation.MethodInvocationTarget; // will throw an exception of type 'System.ArgumentException' | System.Reflection.MethodInfo {System.ArgumentException}
            if (methodInfo == null)
            {
                methodInfo = invocation.Method;
            }

            invocation.Proceed();
            return;
        }
    }

**Comment by stakx** [comment] 2020-12-05 16:17
You've posted a few (partially incomplete) code snippets, but you don't show how they fit together. Could you please post a short but complete & runnable code example showing how you use those types together with DynamicProxy, and then indicate where the reported error happens? Thanks.

**Comment by stakx** [comment] 2021-01-06 12:12
@backjacklao, I've taken another look, but I cannot reproduce any error given your code snippets above. Unless you can provide us with a complete & runnable repro code example, I am going to close this issue in a few days.

**Closed** 2021-01-13 23:02 UTC
Labels: needs-repro
