### ISSUE TITLE
Create proxy with generic constraint fails on Mono

### ISSUE THREAD

**Issue by dtchepak** [castleproject/Core#81] opened 2015-02-19 06:48 UTC
The following works on Windows/.NET but fails on Mac / Mono. Not sure if this is related to #72. This case was derived from [NSubstitute issue 174](https://github.com/nsubstitute/NSubstitute/issues/174). Tested with Castle.Core 3.3.3.

```csharp
using System;
using Castle.DynamicProxy;

namespace Sample {
	class MainClass {
		public static void Main (string[] args) {
			var proxyGenerator = new ProxyGenerator ();
			IInterceptor interceptor = new StandardInterceptor ();		
			var sub = proxyGenerator.CreateInterfaceProxyWithoutTarget<IBar>(new [] {interceptor});	
			Console.WriteLine (sub.GetType());
		}
	}
	public interface IFoo<T>{ }
	public interface IBar{
		void DoStuff<T1, T2> () where T1 : IFoo<T2>;
	}
}
```

Stacktrace:

```
System.ArrayTypeMismatchException: Source array type cannot be assigned to destination array type.
  at at (wrapper stelemref) object:virt_stelemref_sealed_class (intptr,object)
  at Castle.DynamicProxy.Generators.Emitters.GenericUtil.AdjustGenericConstraints (System.Reflection.MethodInfo methodToCopyGenericsFrom, System.Reflection.Emit.GenericTypeParameterBuilder[] newGenericParameters, System.Type[] originalGenericArguments, System.Type[] constraints) [0x00000] in <filename unknown>:0
  at Castle.DynamicProxy.Generators.Emitters.GenericUtil.CopyGenericArguments (System.Reflection.MethodInfo methodToCopyGenericsFrom, System.Collections.Generic.Dictionary`2 name2GenericType, Castle.DynamicProxy.Generators.Emitters.ApplyGenArgs genericParameterGenerator) [0x00000] in <filename unknown>:0
  at Castle.DynamicProxy.Generators.Emitters.GenericUtil.CopyGenericArguments (System.Reflection.MethodInfo methodToCopyGenericsFrom, System.Reflection.Emit.TypeBuilder builder, System.Collections.Generic.Dictionary`2 name2GenericType) [0x00000] in <filename unknown>:0
  at Castle.DynamicProxy.Generators.Emitters.AbstractTypeEmitter.CopyGenericParametersFromMethod (System.Reflection.MethodInfo methodToCopyGenericsFrom) [0x00000] in <filename unknown>:0
  at Castle.DynamicProxy.Generators.InvocationTypeGenerator.Generate (Castle.DynamicProxy.Generators.Emitters.ClassEmitter class, Castle.DynamicProxy.ProxyGenerationOptions options, INamingScope namingScope) [0x00000] in <filename unknown>:0
  at Castle.DynamicProxy.Contributors.InterfaceProxyWithoutTargetContributor.GetInvocationType (Castle.DynamicProxy.Generators.MetaMethod method, Castle.DynamicProxy.Generators.Emitters.ClassEmitter emitter, Castle.DynamicProxy.ProxyGenerationOptions options) [0x00000] in <filename unknown>:0
  at Castle.DynamicProxy.Contributors.InterfaceProxyWithoutTargetContributor.GetMethodGenerator (Castle.DynamicProxy.Generators.MetaMethod method, Castle.DynamicProxy.Generators.Emitters.ClassEmitter class, Castle.DynamicProxy.ProxyGenerationOptions options, Castle.DynamicProxy.Contributors.OverrideMethodDelegate overrideMethod) [0x00000] in <filename unknown>:0
  at Castle.DynamicProxy.Contributors.CompositeTypeContributor.ImplementMethod (Castle.DynamicProxy.Generators.MetaMethod method, Castle.DynamicProxy.Generators.Emitters.ClassEmitter class, Castle.DynamicProxy.ProxyGenerationOptions options, Castle.DynamicProxy.Contributors.OverrideMethodDelegate overrideMethod) [0x00000] in <filename unknown>:0
  at Castle.DynamicProxy.Contributors.CompositeTypeContributor.Generate (Castle.DynamicProxy.Generators.Emitters.ClassEmitter class, Castle.DynamicProxy.ProxyGenerationOptions options) [0x00000] in <filename unknown>:0
  at Castle.DynamicProxy.Generators.InterfaceProxyWithoutTargetGenerator.GenerateType (System.String typeName, System.Type proxyTargetType, System.Type[] interfaces, INamingScope namingScope) [0x00000] in <filename unknown>:0
  at Castle.DynamicProxy.Generators.InterfaceProxyWithTargetGenerator+<>c__DisplayClass1.<GenerateCode>b__0 (System.String n, INamingScope s) [0x00000] in <filename unknown>:0
  at Castle.DynamicProxy.Generators.BaseProxyGenerator.ObtainProxyType (Castle.DynamicProxy.Generators.CacheKey cacheKey, System.Func`3 factory) [0x00000] in <filename unknown>:0
  at Castle.DynamicProxy.Generators.InterfaceProxyWithTargetGenerator.GenerateCode (System.Type proxyTargetType, System.Type[] interfaces, Castle.DynamicProxy.ProxyGenerationOptions options) [0x00000] in <filename unknown>:0
  at Castle.DynamicProxy.DefaultProxyBuilder.CreateInterfaceProxyTypeWithoutTarget (System.Type interfaceToProxy, System.Type[] additionalInterfacesToProxy, Castle.DynamicProxy.ProxyGenerationOptions options) [0x00000] in <filename unknown>:0
  at Castle.DynamicProxy.ProxyGenerator.CreateInterfaceProxyTypeWithoutTarget (System.Type interfaceToProxy, System.Type[] additionalInterfacesToProxy, Castle.DynamicProxy.ProxyGenerationOptions options) [0x00000] in <filename unknown>:0
  at Castle.DynamicProxy.ProxyGenerator.CreateInterfaceProxyWithoutTarget (System.Type interfaceToProxy, System.Type[] additionalInterfacesToProxy, Castle.DynamicProxy.ProxyGenerationOptions options, Castle.DynamicProxy.IInterceptor[] interceptors) [0x00000] in <filename unknown>:0
  at Castle.DynamicProxy.ProxyGenerator.CreateInterfaceProxyWithoutTarget (System.Type interfaceToProxy, Castle.DynamicProxy.IInterceptor[] interceptors) [0x00000] in <filename unknown>:0
  at Castle.DynamicProxy.ProxyGenerator.CreateInterfaceProxyWithoutTarget[IBar] (Castle.DynamicProxy.IInterceptor[] interceptors) [0x00000] in <filename unknown>:0
  at Sample.MainClass.Main (System.String[] args) [0x00018] in Program.cs:12
```

**Comment by kkozmic** [comment] 2015-02-19 08:49
sounds more like a mono issue than DP...

**Comment by kkozmic** [comment] 2015-04-10 00:08
Any update on this?

**Comment by troyschneringer** [comment] 2015-04-17 23:10
updates?

**Comment by jjchiw** [comment] 2015-05-07 10:35
I had I think the same exception with mono 4.0.1

``
* Assertion at sgen-alloc.c:460, condition `*p == NULL' not met

Stacktrace:

  at <unknown> <0xffffffff>
  at Castle.Proxies.ITaskAsync`1Proxy.Build<T> () <0x0012f>
```

Then I tested with [mono-20150507075058] and it works :)

http://www.mono-project.com/docs/getting-started/install/linux/ci-packages/

**Comment by kkozmic** [comment] 2015-05-07 11:16
so is that a newer version than 4.0.1

**Comment by jjchiw** [comment] 2015-05-07 11:38
Yes, it's a build of the CI of mono, It's from yesterday.

**Comment by kkozmic** [comment] 2015-05-07 11:52
cool. Can we close this issue then? It's not really a but in DP after all

**Comment by jonorossi** [comment] 2015-06-22 13:23
@dtchepak I've [committed a fix](https://github.com/castleproject/Core/commit/103c9b76796babba35283c5efa01a395cda03560) for this to the `mono-support` branch, as there is nothing in the mono issue tracker for this and it is an easy workaround for now. I'm working to get all my Mono changes out in the next release, so I'll close this as fixed and I've assigned a milestone to this issue.

@jjchiw Those `Assertion at sgen-alloc.c:460, condition *p == NULL' not met` mono runtime crashes are unrelated to this defect. Looks like it was just a regression and as you mentioned have already been resolved post-4.0.1. See https://bugzilla.xamarin.com/show_bug.cgi?id=28182 and https://github.com/mono/mono/pull/1665 for the details. If we had actually been running our unit tests on mono we would have found this earlier because there are a bunch of our unit tests crashing the mono runtime.

**Closed by jonorossi** 2015-06-22 13:23 UTC

**Comment by RalphBariz** [comment] 2015-06-23 08:51
@jonorossi are your mono changes in the master branch of https://github.com/castleproject/Core?

**Comment by jonorossi** [comment] 2015-06-23 11:15
@RalphBariz not yet, see my comment right before yours.

**Comment by RalphBariz** [comment] 2015-06-23 11:30
@jonorossi It wasnt clear to me if your changes are in none of both branches or just not in unstable-4.0.

**Comment by jonorossi** [comment] 2015-06-23 11:40
@RalphBariz oh, 4.0-unstable is an obsolete branch from 2012, ignore that. I'll get that renamed to avoid future confusion. The changes are only in mono-support.

**Comment by RalphBariz** [comment] 2015-06-23 12:21
@jonorossi thanks for that. Since I'm actually refractoring an app of mine with main focus on mono and linux support, I'll use that branch instead of the nuget package. May make my life easier and you get a tester for the mono support :D

**Comment by jonorossi** [comment] 2015-06-23 12:23
@RalphBariz thanks, please report any problems you run into. If you can help with any of #94, that would be great.

**Comment by RalphBariz** [comment] 2015-06-23 12:31
@jonorossi At the moment I need to focus on an exam, but next week I'll continue, get that branch of castle.core and see what I can do.

**Comment by nbarbettini** [comment] 2015-09-09 17:39
Any update on this? NSubstitute was working fine in `mono-nightly` a few days ago, but it suddenly broke. `alpha` (currently 4.2.0) and `nightly` (currently 4.3.0) both throw these errors when trying to use NSubstitute.

**Comment by jonorossi** [comment] 2015-09-10 07:47
@nbarbettini we hacked around the specific mono runtime crash reported in this defect (i.e. "System.ArrayTypeMismatchException: Source array type cannot be assigned to destination array type.
") in 103c9b76796babba35283c5efa01a395cda03560, not in any released version yet.

We are currently testing against mono 4.0.2, I'll have to get that updated. If you've got a new runtime crash that only occurs under mono 4.2.0+ then could you please log a new defect with more info including at least the stacktrace. Thanks.
