### ISSUE TITLE
Exception thrown when mocking interface that uses generics and byref values.

### ISSUE THREAD

**Issue by jpmnteiro** [castleproject/Core#430] opened 2019-01-29 16:49 UTC
Hey,

I've came across an issue while trying to mock the following interface (cleaned up for clarity):

```
public interface IBase<T>
{
    bool HasValue(in int value);
}
```

It seems to be related to the mixture of generics and byref semantics for value types. If I remove the generic, it works as expected. If I remove the byref (`in`) instead, it works as expected.

I've rummaged through the other issues that mention the byref semantics, but can't seem to find anything related to this, so if anyone has a clue of what I may be doing wrong, comments would be most welcome.

I'm using **NSubstitute 4.0.0-rc1** with **Castle.Core 4.3.1** on a `netcoreapp2.0` and `net472` project (using .NET Core SDK 2.2.100-preview3-009430).

Here's the stack trace (sensitive information clipped):

```
Castle.DynamicProxy.ProxyGenerationException : There was an error in static constructor on type Castle.Proxies.IBase`1Proxy. This is likely a bug in DynamicProxy. Please report it.
  ----> System.Reflection.TargetInvocationException : Exception has been thrown by the target of an invocation.
  ----> System.TypeInitializationException : The type initializer for 'Castle.Proxies.IBase`1Proxy' threw an exception.
  ----> System.MissingMethodException : Method not found: 'Boolean UnitTests.IBase`1.HasValue(Int32 ByRef)'.
   at Castle.DynamicProxy.Internal.TypeUtil.SetStaticField(Type type, String fieldName, BindingFlags additionalFlags, Object value)
   at Castle.DynamicProxy.Generators.InterfaceProxyWithoutTargetGenerator.GenerateType(String typeName, Type proxyTargetType, Type[] interfaces, INamingScope namingScope)
   at Castle.DynamicProxy.Generators.InterfaceProxyWithTargetGenerator.<>c__DisplayClass6_0.<GenerateCode>b__0(String n, INamingScope s)
   at Castle.DynamicProxy.Generators.BaseProxyGenerator.ObtainProxyType(CacheKey cacheKey, Func`3 factory)
   at Castle.DynamicProxy.ProxyGenerator.CreateInterfaceProxyWithoutTarget(Type interfaceToProxy, Type[] additionalInterfacesToProxy, ProxyGenerationOptions options, IInterceptor[] interceptors)
   at NSubstitute.Proxies.CastleDynamicProxy.CastleDynamicProxyFactory.GenerateProxy(ICallRouter callRouter, Type typeToProxy, Type[] additionalInterfaces, Object[] constructorArguments)
   at NSubstitute.Core.SubstituteFactory.Create(Type[] typesToProxy, Object[] constructorArguments, SubstituteConfig config)
   at NSubstitute.Substitute.For[T](Object[] constructorArguments)
   at UnitTests.CommonTopicBranchFixture.Test() in Test.cs:line ...
--TargetInvocationException
   at System.RuntimeFieldHandle.SetValue(RtFieldInfo field, Object obj, Object value, RuntimeType fieldType, FieldAttributes fieldAttr, RuntimeType declaringType, Boolean& domainInitialized)
   at System.Reflection.RtFieldInfo.InternalSetValue(Object obj, Object value, BindingFlags invokeAttr, Binder binder, CultureInfo culture, StackCrawlMark& stackMark)
   at System.Reflection.RtFieldInfo.SetValue(Object obj, Object value, BindingFlags invokeAttr, Binder binder, CultureInfo culture)
   at Castle.DynamicProxy.Internal.TypeUtil.SetStaticField(Type type, String fieldName, BindingFlags additionalFlags, Object value)
--TypeInitializationException

--MissingMethodException
   at Castle.Proxies.IBase`1Proxy..cctor()
```

And here's a complete test case (using NUnit):

```
public interface IBase<T>
{
    bool HasValue(in int value);
}

[TestFixture]
public class MockTest
{
    [Test]
    public void MockingGenericsAndByRef()
    {
        Substitute.For<IBase<int>>();
    }
}
```

**Comment by stakx** [comment] 2019-02-01 07:55
@jpmnteiro, thank you for taking the time to report this problem.

This might be a duplicate of #339, which was caused by a Reflection bug (https://github.com/dotnet/corefx/issues/29254) which should have been fixed already (https://github.com/dotnet/coreclr/pull/17881), not sure why the problem resurfaces now. I'll need to give this a closer look.

**Comment by jpmnteiro** [comment] 2019-02-01 14:20
@stakx I originally thought so to, but I have other interfaces with byref semantics for value types and they are all being mocked correctly, hence the issue report.

Let me know if there's anything I can help with (other test cases, etc).

**Comment by stakx** [comment] 2019-02-06 12:04
@jpmnteiro - It's slowly coming back to me now. The scenario where you have a method with value type by-ref semantics in a generic type still doesn't work because the bug in the .NET Core runtime never got fixed; see https://github.com/dotnet/corefx/issues/29254#issuecomment-460997723 for a brief summary why.

Back then, given their documentation, I just couldn't seem to get my dotnet/coreclr & dotnet/corefx dev environment into a state where it would run unit tests reliably... and after having caused one regression in the repo, I wasn't too keen on going on without the unit test safety net firmly in place. That's why I abandoned (and eventually forgot about) that issue. (Maybe I should take another look at their dev docs and see if I can set things up correctly on my end this time around.)

**Comment by stakx** [comment] 2019-03-11 17:00
I had one more go at setting up a fresh copy of the dotnet/coreclr repo for local development... and failed utterly. Not sure what changed since last time I tried, but now I can't even get the repo to start compiling anymore, despite following their instructions.

With other words, fixing this might take some time...

**Comment by stakx** [comment] 2021-01-07 18:50
A bug fix for this has happened inside CoreCLR, but is only scheduled for .NET 6.

It occurred to me only today that this CLR bug can be circumvented. As I stated in the CoreCLR issue (link above), the problem is ultimately caused by System.Reflection.Emit encoding an incorrect method signature for `ldtoken <methodToken>` under certain conditions (generics + `in` parameter modifier). There is a single code location in DynamicProxy where this `ldtoken` form is used:

https://github.com/castleproject/Core/blob/5f2865267cbd457fe9c1274eb7a397520735048f/src/Castle.Core/DynamicProxy/Generators/Emitters/SimpleAST/MethodTokenExpression.cs#L35

`MethodTokenExpression` is supposed to put a `MethodInfo` object on the evaluation stack. This is currently implemented as `ldtoken` + `MethodBase.GetMethodFromHandle`, which is the most efficient way to get this done... but it's not the only way. We could emit code that goes through Reflection instead.

Say you have a `MethodInfo method` object for some method `[public] void M()`, and you want to emit code that leaves a `MethodInfo` for that method on the evaluation stack. This is how we do it today:

```csharp
il.Emit(OpCode.Ldtoken, method);
il.Emit(OpCode.Call, typeof(MethodBase).GetMethod("GetMethodFromHandle", ...));
```

We could also do this:
```csharp
il.Emit(OpCode.Ldtoken, method.DeclaringType);
il.Emit(OpCode.Call, typeof(Type).GetMethod("GetTypeFromHandle", ...));
il.Emit(OpCode.Ldstr, method.Name);
il.Emit(OpCode.Callvirt, typeof(Type).GetMethod("GetMethod", new[] { typeof(string) }));
```

Some things to note:

* A Reflection-based solution will very likely perform much worse than a direct `ldtoken`, so that code should only be emitted when absolutely necessary.
* The Reflection query to find the right method can get much more complex once generic parameters get involved. One has to emit code for fetching the generic method definition, then resolve that method through `Module.ResolveMethod`, and finally reapplying the generic arguments (which can be type parameters!).

This isn't trivial, but from a few experiments that I've run, it's feasible.

This workaround seems worth doing to me because it'll be a whole other while until everyone uses .NET 6. In the meantime, people are using `in` parameters and generics and probably need DynamicProxy to be able to handle those.

**Comment by jonorossi** [comment] 2021-01-19 13:06
I agree that it would be too much work to do a complete workaround, method signature semantics are crazy 😄 . There is also a chance that they backport it to .NET 5.0 sometime this year if it becomes a bigger problem, sounds like there is quite a few people having issues with `ReadOnlySpan` and dynamic code generation.

Shouldn't we be able to detect the situation where the CLR will blow up and do the partial workaround for some cases so the performance impact is only going to be for that situation? We've done similar things many times before especially in .NET Framework 2.0 and 3.5 days.

**Comment by stakx** [comment] 2021-01-19 14:38
Yes, we could build in some recognition logic. We'd have to emit a test type & test method into a separate dynamic module (`DynamicMethod` won't do as those aren't affected) once to see if the runtime is affected by the bug. If so, we can check whether the method or its declaring type is generic, and whether it has parameters with cmods.

If you're fine with a partial fix for the easy cases, I can prepare a PR.

**Comment by jonorossi** [comment] 2021-01-19 14:49
I'd just implement the workaround for all runtimes without trying to detect if the runtime is broken for now, since they all are.

**Comment by stakx** [comment] 2021-04-21 21:11
I've tried implementing the limited workaround a few weeks ago. Even that turned out to be more difficult than expected, because it isn't just the `ldtoken` instruction that's affected (like I initially thought), but `[virt]call` (and a few others) too &ndash; the latter are used in many places across DP where it's more complicated to insert the workaround... I'm not sure I can get this done anytime soon.

Given that .NET 6 Preview is now available, and that it fixes this issue, there's now a good alternative to the workaround &ndash; the latter is now needed only for older framework versions, so it's lost a little bit of importance.

**Comment by stakx** [comment] 2022-05-12 17:49
I think we can close this issue.

.NET 6 (where it has been resolved) is now an official LTS release and we target that runtime directly. New C# language features keep driving people to adopt current .NET runtimes, and Microsoft hasn't backported the runtime bugfix to the older .NET Framework. If they don't make the effort to keep newer C# language features working on an older platform, maybe it's not our job to jump in and hide that.

Finally, given that even a limited workaround would be difficult and costly to implement, I suggest we invest our time elsewhere and close this. Only thing I'm unsure about is whether we ought to document this as a limitation, and if so, where?

Any thoughts?

**Comment by jonorossi** [comment] 2022-05-14 12:29
> If they don't make the effort to keep newer C# language features working on an older platform, maybe it's not our job to jump in and hide that.

Completely agree. If our users won't upgrade their runtime, they likely won't upgrade our library either. It is great to see quite a lot of CLR and reflection fixes going into the last few .NET Core releases, .NET Framework is mature, no reason to risk backporting anything.

> Only thing I'm unsure about is whether we ought to document this as a limitation on older runtimes; and if so, where?

Can we instead add a unit test that only runs on .NET 6?

**Comment by stakx** [comment] 2022-05-14 13:50
> Can we instead add a unit test that only runs on .NET 6?

Oh, good idea. I'll add one or two.

**Closed** 2022-05-14 15:52 UTC
