### ISSUE TITLE
Update referenced package versions

### ISSUE THREAD

**Issue by sebastienros** [castleproject/Core#264] opened 2017-05-31 18:02 UTC
The current Nuget package references System.ComponentModel.TypeConverter **4.0.1** which actually doesn't exist.

From the `project.json` file it should have been `4.1.0` so I can't explain where it's taking this version from.

**Comment by jonorossi** [comment] 2017-06-01 14:53
Duplicate of #239, the fix hasn't been released yet.

**Closed by jonorossi** 2017-06-01 14:53 UTC
