### ISSUE TITLE
.NET Core - unit test runner returning exit code 3

### ISSUE THREAD

**Issue by jonorossi** [castleproject/Core#130] opened 2016-02-25 17:25 UTC
Build 23 failed:

> Tests passed: 266, ignored: 1; exit code 3 (new) 	
http://builds.castleproject.org/viewType.html?buildTypeId=CoreNetCore_MasterNetCore

**Comment by rjdevereux** [comment] 2016-02-27 01:20
Any advice on how to engage on this?  Not sure how to start without being able to see the build steps so I can make sense of the build log.

Thanks

**Comment by blairconrad** [comment] 2016-02-27 02:42
@rjdevereux, not trying to steal work from you, but I was in the midst of thinking about trying to start working on this, and I can already see the build steps. If you and @jonorossi don't mind, I will actually try to start working on this…

**Comment by blairconrad** [comment] 2016-02-27 03:26
Hmm. With the latest changes from @jeremymeng, we don't get so far as to run the tests. Stuck on 

```
…\src\Castle.Core.Tests\project.json(9,20): error NU1002: The dependency Castle.Core 3.3.4 in project Castle.Core.Tests does not support framework DNXCore,Version=v5.0.
```

which I can reproduce at home. Yay! I'm not sure what to do, though. We appear to build Castle.Core for `dotnet5.4`, but then try to build `Castle.Core.Tests` for framework `dnxcore50`.It looks like 0a55378fd9cc changed Castle.Core to build `dotnet5.4` instead of `dotnet`. Unfortunately, this is all Greek to me. Other than "it's different", I don't understand what the differences mean. Changing Castle.Core.Tests to build against framework `dotnet5.4` just made it angry that we don't have a proper xUnit:

```
…\src\Castle.Core.Tests\project.json(15,25): error NU1002: The dependency xunit.runner.dnx 2.1.0-rc1-build204 in project Castle.Core.Tests does not support framework .NETPlatform,Version=v5.4.
```

Out of my depth and sleepy. Will come back in several hours. Sorry.

**Comment by jeremymeng** [comment] 2016-02-27 03:29
I noticed it on the build too...silly question: do you have rc1 dnx installed?

**Comment by jeremymeng** [comment] 2016-02-27 03:32
I think it might be an issue of dnx.  The tests run fine from Visual Studio test runner.  However doing `dnx test` from command-line prompt would randomly failed.  It seems that dnx crash/exit silently.

**Comment by rjdevereux** [comment] 2016-02-27 08:51
@blairconrad go for it!  I won't be offended.  @jeremymeng what do you expect dnx test to print out?  Last night I thought it was exiting after running only a few tests, but running it again, it looks like it's only generating output for skipped tests, but maybe it's still running all the tests.

**Comment by blairconrad** [comment] 2016-02-27 11:19
@jeremymeng, I used the same "download dnvm, download dnx, download packages, compile" commands that the TeamCity server did:

```powershell
$dnxPath = Join-Path (Get-Location) ".dnx\bin"

Write-Host "Downloading dnvm to: $dnxPath"
if (!(Test-Path $dnxPath)) { md $dnxPath | Out-Null }

$dnvmPs1Path = Join-Path $dnxPath "dnvm.ps1"
$dnvmCmdPath = Join-Path $dnxPath "dnvm.cmd"

$wc = New-Object System.Net.WebClient
$wc.DownloadFile('https://raw.githubusercontent.com/aspnet/Home/dev/dnvm.ps1', $dnvmPs1Path)
$wc.DownloadFile('https://raw.githubusercontent.com/aspnet/Home/dev/dnvm.cmd', $dnvmCmdPath)
```

```cmd
set DNX_HOME=%CD%\.dnx
set PATH=%DNX_HOME%\bin;%PATH%

dnvm install 1.0.0-beta8 -runtime coreclr -arch x86
```

```cmd
set DNX_HOME=%CD%\.dnx
set PATH=%DNX_HOME%\bin;%DNX_HOME%\runtimes\dnx-coreclr-win-x86.1.0.0-beta8\bin;%PATH%

dnx --version

dnu restore
```

```cmd
set DNX_HOME=%CD%\.dnx
set PATH=%DNX_HOME%\bin;%DNX_HOME%\runtimes\dnx-coreclr-win-x86.1.0.0-beta8\bin;%PATH%

dnu build src/Castle.Core src/Castle.Core.Tests --configuration Release --out build/NETCORE q
```

I will try to update these to get rc1. Thanks!

@jonorossi, this dovetails into something I was thinking anyhow - instead of putting all the download/compile/whatever commands in TeamCity steps, we may be better off having them in `.ps1` and `.cmd` files. That way, they're visible to everyone (like @rjdevereux) and runnable by everyone (like me and @jeremymeng). In general I find it a better approach anyhow, as there's more visibility into changes (they're in the git history) and it decouples the package from the CI server (in case you ever wanted to move, not saying it's likely). What think you?

**Comment by jonorossi** [comment] 2016-02-27 12:09
@blairconrad yep, exactly something I want, thought I created an issue for that specifically but missed that one. I threw those hardcoded steps in TeamCity to just work out what was needed and get something going because dnx was all new at the time, never intended them to stay.

This flows into #134, however for now lets get them into the `build.cmd` (or a file it calls) we've already got in the repo.

**Comment by blairconrad** [comment] 2016-02-27 12:09
@jeremymeng, I updated to rc1 dnx and got farther. Thanks!
I think the mechanism does a little more work in the "download dnx" stage than it has to (in that it _always_ seems do download and compile packages), but it's certainly functional!

Here's the modified 5-step build procedure:

[build_netcore_and_run_tests.zip](https://github.com/castleproject/Core/files/149323/build_netcore_and_run_tests.zip)

@jonorossi, would you like me to update the build server to include the changed instructions, either by modifying the build steps to include the changes directly, or by adding cmds and ps1s in the buildscripts directory? I can work on a private build configuration for a bit, if you're worried about me mucking things up.

**Comment by blairconrad** [comment] 2016-02-27 12:09
Oh, no! Crossing comments!

**Comment by blairconrad** [comment] 2016-02-27 12:10
@jonorossi, I'm running out for errands soon, but will return to the build changes over the weekend. I'll submit a PR to include the steps somewhere in or hanging off the build.cmd and if that goes well we can update the build configuration.

**Comment by jonorossi** [comment] 2016-02-27 12:13
@blairconrad sounds good, let me know if you've got questions about the build scripts, they are very complicated and were written quite a long time ago after we moved from NAnt. I'd like to see the .NET Core stuff in the batch files rather than as deep as MSBuild (which the batch files call).

**Comment by blairconrad** [comment] 2016-02-27 12:15
In the meantime, the error I got to (in case anyone's curious) is 


```cmd
C:\PortableApps\Documents\Source\GitHub\Castle.Core>dnx -p src/Castle.Core.Tests test
xUnit.net DNX Runner (64-bit DNXCore 5.0)
  Discovering: Castle.Core.Tests
  Discovered:  Castle.Core.Tests
  Starting:    Castle.Core.Tests
    Castle.Core.Tests.Resources.FileResourceFactoryTestCase.CreateWithRelativePath [FAIL]
      Castle.Core.Resource.ResourceException : File C:\PortableApps\Documents\Source\GitHub\Castle.Core\Core.Tests\Resources\file1.txt could not be found
      Stack Trace:
        C:\PortableApps\Documents\Source\GitHub\Castle.Core\src\Castle.Core\Core\Resource\FileResource.cs(117,0): at Castle.Core.Resource.FileResource.CheckFileExists(String path)
        C:\PortableApps\Documents\Source\GitHub\Castle.Core\src\Castle.Core\Core\Resource\FileResource.cs(102,0): at Castle.Core.Resource.FileResource.CreateStreamFromPath(String resourcePath, String rootPath)
        C:\PortableApps\Documents\Source\GitHub\Castle.Core\src\Castle.Core\Core\Resource\FileResource.cs(84,0): at Castle.Core.Resource.FileResource.CreateStreamFromUri(CustomUri resource, String rootPath)
        C:\PortableApps\Documents\Source\GitHub\Castle.Core\src\Castle.Core\Core\Resource\FileResource.cs(33,0): at Castle.Core.Resource.FileResource.<>c__DisplayClass2_0.<.ctor>b__0()
        C:\PortableApps\Documents\Source\GitHub\Castle.Core\src\Castle.Core\Core\Resource\AbstractStreamResource.cs(46,0): at Castle.Core.Resource.AbstractStreamResource.GetStreamReader()
        C:\PortableApps\Documents\Source\GitHub\Castle.Core\src\Castle.Core.Tests\Core.Tests\Resources\FileResourceFactoryTestCase.cs(71,0): at Castle.Core.Tests.Resources.FileResourceFactoryTestCase.CreateWithRelativePath()
    Castle.Core.Tests.Resources.FileResourceFactoryTestCase.CreateWithRelativePathAndContext [FAIL]
      Castle.Core.Resource.ResourceException : File C:\PortableApps\Documents\Source\GitHub\Castle.Core\Core.Tests\Resources\file1.txt could not be found
      Stack Trace:
        C:\PortableApps\Documents\Source\GitHub\Castle.Core\src\Castle.Core\Core\Resource\FileResource.cs(117,0): at Castle.Core.Resource.FileResource.CheckFileExists(String path)
        C:\PortableApps\Documents\Source\GitHub\Castle.Core\src\Castle.Core\Core\Resource\FileResource.cs(102,0): at Castle.Core.Resource.FileResource.CreateStreamFromPath(String resourcePath, String rootPath)
        C:\PortableApps\Documents\Source\GitHub\Castle.Core\src\Castle.Core\Core\Resource\FileResource.cs(84,0): at Castle.Core.Resource.FileResource.CreateStreamFromUri(CustomUri resource, String rootPath)
        C:\PortableApps\Documents\Source\GitHub\Castle.Core\src\Castle.Core\Core\Resource\FileResource.cs(41,0): at Castle.Core.Resource.FileResource.<>c__DisplayClass3_0.<.ctor>b__0()
        C:\PortableApps\Documents\Source\GitHub\Castle.Core\src\Castle.Core\Core\Resource\AbstractStreamResource.cs(46,0): at Castle.Core.Resource.AbstractStreamResource.GetStreamReader()
        C:\PortableApps\Documents\Source\GitHub\Castle.Core\src\Castle.Core.Tests\Core.Tests\Resources\FileResourceFactoryTestCase.cs(83,0): at Castle.Core.Tests.Resources.FileResourceFactoryTestCase.CreateWithRelativePathAndContext()
    Castle.Core.Tests.Resources.FileResourceFactoryTestCase.CreateWithAbsolutePath [FAIL]
      Castle.Core.Resource.ResourceException : File C:\PortableApps\Documents\Source\GitHub\Castle.Core\Core.Tests\Resources\file1.txt could not be found
      Stack Trace:
        C:\PortableApps\Documents\Source\GitHub\Castle.Core\src\Castle.Core\Core\Resource\FileResource.cs(117,0): at Castle.Core.Resource.FileResource.CheckFileExists(String path)
        C:\PortableApps\Documents\Source\GitHub\Castle.Core\src\Castle.Core\Core\Resource\FileResource.cs(102,0): at Castle.Core.Resource.FileResource.CreateStreamFromPath(String resourcePath, String rootPath)
        C:\PortableApps\Documents\Source\GitHub\Castle.Core\src\Castle.Core\Core\Resource\FileResource.cs(84,0): at Castle.Core.Resource.FileResource.CreateStreamFromUri(CustomUri resource, String rootPath)
        C:\PortableApps\Documents\Source\GitHub\Castle.Core\src\Castle.Core\Core\Resource\FileResource.cs(33,0): at Castle.Core.Resource.FileResource.<>c__DisplayClass2_0.<.ctor>b__0()
        C:\PortableApps\Documents\Source\GitHub\Castle.Core\src\Castle.Core\Core\Resource\AbstractStreamResource.cs(46,0): at Castle.Core.Resource.AbstractStreamResource.GetStreamReader()
        C:\PortableApps\Documents\Source\GitHub\Castle.Core\src\Castle.Core.Tests\Core.Tests\Resources\FileResourceFactoryTestCase.cs(61,0): at Castle.Core.Tests.Resources.FileResourceFactoryTestCase.CreateWithAbsolutePath()
    Castle.DynamicProxy.Tests.ClassWithAttributesTestCase.EnsureProxyHasAttributesOnOnReturn [SKIP]
      Not supported. Is it possible? There seems to be no API to allow that.
```

So at least there seems to be a relative path problem resolving `file1.txt` (which lives in `src\Castle.Core.Tests\Core.Tests\Resources\file1.txt`, but is referred to as `"CastleTests.Core.Tests.Resources.file1.txt": "Core.Tests/Resources/file1.txt"` in `namedResources` in `Castle.Core.Tests\project.json).

Then there's the `SKIP` toward the end, which may be related or not.

**Comment by blairconrad** [comment] 2016-02-27 12:17
> I'd like to see the .NET Core stuff in the batch files rather than as deep as MSBuild (which the batch files call).

My naive thought was to add another case in the initial set of IF statements and then just shell out to a separate cmd to do the netcore build. It's not super-pretty, and may not be best for long-term use, but at least would be visible and a little easy to manage while there's (expected) higher churn…
but I will do whatever you like.

**Comment by jonorossi** [comment] 2016-02-27 12:20
@blairconrad sounds like a plan, we just need to get it out of TeamCity to unblock this task. Baby steps are the best way.

Ignore the `SKIP`, it is like xUnit.net reporting an ignored test: https://github.com/castleproject/Core/blob/master/src/Castle.Core.Tests/ClassWithAttributesTestCase.cs#L92-L98

**Comment by blairconrad** [comment] 2016-02-27 13:06
> Ignore the SKIP

Whoops! My netcore was behind. How embarrassing.

**Comment by blairconrad** [comment] 2016-02-27 13:16
Hm. That makes no sense, since I was getting the `[SKIP]` but I swear I looked at that test before pulling, and there was no `Ignore` on it. Odd.
Let's put it down to "coding while still in the middle of the first cup of tea".

**Comment by jonorossi** [comment] 2016-02-27 13:40
@blairconrad yep, not sure what you were looking at, that test has been ignored in master since 2010 :smile:

**Comment by jeremymeng** [comment] 2016-02-28 04:08
> what do you expect dnx test to print out?

I would expect a status line about passing/failing numbers, similar to

```
=== TEST EXECUTION SUMMARY ===
   Moq.NetCore.Tests  Total: 661, Errors: 0, Failed: 1, Skipped: 7, Time: 3.579s```

**Comment by blairconrad** [comment] 2016-02-28 04:21
Hmm. Disheartening. After my changes for #140, I'm getting

```
xUnit.net DNX Runner (64-bit DNXCore 5.0)
  Discovering: Castle.Core.Tests
  Discovered:  Castle.Core.Tests
  Starting:    Castle.Core.Tests
```

(on a good run. Sometimes 3 failures, including `Castle.Core.Tests.Resources.FileResourceFactoryTestCase.CreateWithRelativePath [FAIL]`. But in any case, no nice summary.)

**Comment by jeremymeng** [comment] 2016-02-28 07:05
I believe the exit code of "3" is from the three resource factory tests. However the dnx process seems to exit randomly without waiting for all tests to finish.

@bradwilson Brad, do you have any ideas? Is it related to TPL? The tests run fine in VS. Castle.Core.Tests project uses a shim to run Nunit tests: https://github.com/castleproject/Core/blob/netcore/src/Castle.Core.Tests/Compatibility/XUnitNetShim.cs

**Comment by blairconrad** [comment] 2016-02-28 12:19
@jeremymeng, I also guessed that the "3" was related to the failing test, but was thrown by the lack of output. Your observation about the dnx process exiting randomly is interesting.

**Comment by rjdevereux** [comment] 2016-02-28 18:31
This looks related

https://github.com/xunit/dnx.xunit/blob/2.1-rc1/src/xunit.runner.dnx/Program.cs#L124

**Comment by blairconrad** [comment] 2016-02-28 20:34
@rjdevereux, it's possible, but I'm skeptical. I think if this were the cause, would we not see the error message printed?
The time the test takes is also suspect, since the test run [started at 15:10:05](http://builds.castleproject.org/viewLog.html?tab=buildLog&logTab=tree&filter=debug&expand=all&buildId=13096#_state=585&focus=585), but the error isn't [reported until 15:10:29](http://builds.castleproject.org/viewLog.html?tab=buildLog&logTab=tree&filter=debug&expand=all&buildId=13096#_focus=1198), which seems like a long time to figure out that there's an argument exception.

Then again, on my local build with my code from #140, I'm consistently getting an error code of 1, regardless of how many tests seem to have failed. Maybe you're right. I'm not sure how to figure that out yet…

**Comment by bradwilson** [comment] 2016-02-28 23:27
I've seen cases where people wrote tests which wrapped/replaced the console output stream and they forgot to restore it, thus killing all further output.

**Comment by jeremymeng** [comment] 2016-02-29 04:58
@bradwilson you are right! Thanks man! I opened #143 and submitted a PR.

**Comment by jonorossi** [comment] 2016-02-29 05:02
@bradwilson @jeremymeng makes sense, I guess we never had the problem before because NUnit has multiple AppDomains on .NET Framework so our ConsoleLogger unit tests didn't mess with NUnit.

**Comment by bradwilson** [comment] 2016-02-29 05:29
Right. No app domains in DNX / .NET Core. :)

**Comment by jonorossi** [comment] 2016-02-29 05:40
@bradwilson any chance xUnit.net could just grab a reference to out and error when it starts to prevent this catching anyone else or if our teardown doesn't get called for some reason?

**Comment by bradwilson** [comment] 2016-02-29 05:46
In theory this seems like a good idea, but the reality is that there's a whole ton of things that people could hook that would mess us up. What makes Console special? Frankly, it's pretty darn rare to override Console. :smiley:

**Comment by jonorossi** [comment] 2016-02-29 05:50
@bradwilson only because you've seen others do it too :smile:, but as I mentioned in my edit it is more involved than just two streams, and once people fix their tests it should be sorted.

**Comment by blairconrad** [comment] 2016-03-01 04:47
All: the new build target is there, and seemed to have worked. And running the tests from the test directory worked around the 3 failures. Thanks for doing most of the work!

**Closed** 2016-03-01 04:53 UTC
Labels: up for grabs
