### ISSUE TITLE
Visual Studio 2017 Castle Core depends on System.ComponentModel.TypeConverter but was not found

### ISSUE THREAD

**Issue by moliveto** [castleproject/Core#296] opened 2017-08-19 15:36 UTC
Severity	Code	Description	Project	File	Line	Suppression State
Warning	NU1603	Castle.Core 4.0.0 depends on System.ComponentModel.TypeConverter (>= 4.0.1) but System.ComponentModel.TypeConverter 4.0.1 was not found. An approximate best match of System.ComponentModel.TypeConverter 4.1.0 was resolved.	Provider	D:\VS 2017\Interception\Provider\Provider.csproj	1

**Comment by moliveto** [comment] 2017-08-19 15:36
see
moq/moq4#375

**Comment by jonorossi** [comment] 2017-08-22 05:43
Duplicate of #239, the fix was released in Castle Core 4.1.0.

**Closed by jonorossi** 2017-08-22 05:43 UTC
